name: Deploy React App
on: push
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install project dependencies 
        run: npm ci 
      - name: Lint project 
        run: npm run lint
      - name: Lint 
        run: |
          echo Linted ...
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install project dependencies 
        run: npm ci 
      - name: Build project 
        run: npm run build
      - name: Deploy 
        run: |
          echo Has built ...
          
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Get repository code
        uses: actions/checkout@v4
      - name: Install project dependencies 
        run: npm ci 
      - name: Build project 
        run: npm run build
      - name: Deploy 
        run: |
          echo Deploying ...
    
