name: Test React App
on: 
  push: 
    branches: 
    - main 
    - features 
    - form/feature
jobs:
  test-process:
    runs-on: ubuntu-latest
    steps:
     - name: Deploy
        run: |
          echo Has been tested ...